server:
  port: 8083

spring:
  application:
    name: product-query-service

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9200
      repositories:
        enabled: true

