version: "3.8"
name: "product-query"
services:
  elasticsearch-db:
    extends:
      file: databases.yml
      service: elasticsearch_db
  kibana_ui:
    extends:
      file: databases.yml
      service: kibana_ui

networks:
  elasticsearch_db_network:
    driver: bridge
volumes:
  elasticsearch_db_data:
    driver: local